# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: pyodb ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-fedora:

    runs-on: ubuntu-latest
    container: fedora

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
            #"3.11"
            #"3.12"
            #"3.13"
      - name: Install dependencies for OS
	run: dnf install -y make gcc
      - name: Create venv
        run: python -m venv venv
      - name: Install requirements
        run: ./venv/bin/pip install -r requirements.txt
  
  build-ubuntu:

    runs-on: ubuntu-latest
    container: ubuntu 

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
            #"3.11"
            #"3.12"
            #"3.13"
      - name: Install dependencies for OS
        run: |
          apt-get update
          apt-get install -y gcc make gtk3
      - name: Create venv
        run: python -m venv venv
      - name: Install requirements
        run: ./venv/bin/pip install -r requirements.txt
  
  build-arch:

    runs-on: ubuntu-latest
    container: archlinux 

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
            #"3.11"
            #"3.12"
            #"3.13"
      - name: Install dependencies for OS
        run: |
          pacman -Syu
          pacman -Syu -y gcc make gtk3
      - name: Create venv
        run: python -m venv venv
      - name: Install requirements
        run: ./venv/bin/pip install -r requirements.txt
