# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: pyodb ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build-fedora:

    runs-on: ubuntu-latest
    container: fedora

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies for OS
        run: |
          dnf install -y make automake gcc gcc-c++ kernel-devel python-devel
      - name: Create venv
        run: python -m venv venv
      - name: Install requirements
        run: |
          ./venv/bin/pip install setuptools
          ./venv/bin/pip install -r requirements.txt --verbose
  
  build-ubuntu:

    runs-on: ubuntu-latest
    container: ubuntu 

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies for OS
        run: |
          apt-get update
          apt-get install -y build-essential python3-dev libgtk-3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev freeglut3-dev libwebkitgtk-1.0-0-dev
      #apt-get install -y libjpeg-dev libpng-dev libtiff-dev libsdl-dev libnotify-dev libsm-dev
      - name: Create venv
        run: python -m venv venv
      - name: Install requirements
        run: ./venv/bin/pip install setuptools
        run: ./venv/bin/pip install -r requirements.txt --verbose
  
  build-archlinux:

    runs-on: ubuntu-latest
    container: archlinux 

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies for OS
        run: |
          pacman -Syu
          pacman -Syu --noconfirm base-devel gtk3
      - name: Create venv
        run: python -m venv venv
      - name: Install requirements
        run: |
          ./venv/bin/pip install setuptools
          ./venv/bin/pip install -r requirements.txt --verbose
  
  build-windows:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
            #"3.11"
            #"3.12"
            #"3.13"
      #- name: Install dependencies for OS
      #  run: |
      #    dnf install -y make automake gcc gcc-c++ kernel-devel python-devel
      - name: Create venv
        run: python -m venv venv
      - name: Install requirements
        run: |
          .\venv\Scripts\activate
          pip install -r requirements.txt --verbose
  
  build-macos:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
            #"3.11"
            #"3.12"
            #"3.13"
      - name: Create venv
        run: python -m venv venv
      - name: Install requirements
        run: |
          #./venv/bin/pip install setuptools
          ./venv/bin/pip install -r requirements.txt --verbose
